/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompletarPerfilRouteImport } from './routes/completar-perfil'
import { Route as DatosRouteImport } from './routes/datos'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as MiCuentaRouteImport } from './routes/mi-cuenta'
import { Route as MisSolicitudesRouteImport } from './routes/mis-solicitudes'
import { Route as ModeracionRouteImport } from './routes/moderacion'
import { Route as PublicarRouteImport } from './routes/publicar'
import { Route as TerminosRouteImport } from './routes/terminos'
import { Route as ArticulosIndexRouteImport } from './routes/articulos.index'
import { Route as ArticulosIdRouteImport } from './routes/articulos.$id'
import { Route as MisPublicacionesIndexRouteImport } from './routes/mis-publicaciones.index'
import { Route as MisPublicacionesIdRouteImport } from './routes/mis-publicaciones.$id'
import { Route as VecinoIdRouteImport } from './routes/vecino.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompletarPerfilRoute = CompletarPerfilRouteImport.update({
  id: '/completar-perfil',
  path: '/completar-perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const DatosRoute = DatosRouteImport.update({
  id: '/datos',
  path: '/datos',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const MiCuentaRoute = MiCuentaRouteImport.update({
  id: '/mi-cuenta',
  path: '/mi-cuenta',
  getParentRoute: () => rootRouteImport,
} as any)
const MisSolicitudesRoute = MisSolicitudesRouteImport.update({
  id: '/mis-solicitudes',
  path: '/mis-solicitudes',
  getParentRoute: () => rootRouteImport,
} as any)
const ModeracionRoute = ModeracionRouteImport.update({
  id: '/moderacion',
  path: '/moderacion',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicarRoute = PublicarRouteImport.update({
  id: '/publicar',
  path: '/publicar',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminosRoute = TerminosRouteImport.update({
  id: '/terminos',
  path: '/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticulosIndexRoute = ArticulosIndexRouteImport.update({
  id: '/articulos/',
  path: '/articulos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticulosIdRoute = ArticulosIdRouteImport.update({
  id: '/articulos/$id',
  path: '/articulos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MisPublicacionesIndexRoute = MisPublicacionesIndexRouteImport.update({
  id: '/mis-publicaciones/',
  path: '/mis-publicaciones/',
  getParentRoute: () => rootRouteImport,
} as any)
const MisPublicacionesIdRoute = MisPublicacionesIdRouteImport.update({
  id: '/mis-publicaciones/$id',
  path: '/mis-publicaciones/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const VecinoIdRoute = VecinoIdRouteImport.update({
  id: '/vecino/$id',
  path: '/vecino/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/completar-perfil': typeof CompletarPerfilRoute
  '/datos': typeof DatosRoute
  '/entrar': typeof EntrarRoute
  '/mi-cuenta': typeof MiCuentaRoute
  '/mis-solicitudes': typeof MisSolicitudesRoute
  '/moderacion': typeof ModeracionRoute
  '/publicar': typeof PublicarRoute
  '/terminos': typeof TerminosRoute
  '/articulos/$id': typeof ArticulosIdRoute
  '/mis-publicaciones/$id': typeof MisPublicacionesIdRoute
  '/vecino/$id': typeof VecinoIdRoute
  '/articulos/': typeof ArticulosIndexRoute
  '/mis-publicaciones/': typeof MisPublicacionesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/completar-perfil': typeof CompletarPerfilRoute
  '/datos': typeof DatosRoute
  '/entrar': typeof EntrarRoute
  '/mi-cuenta': typeof MiCuentaRoute
  '/mis-solicitudes': typeof MisSolicitudesRoute
  '/moderacion': typeof ModeracionRoute
  '/publicar': typeof PublicarRoute
  '/terminos': typeof TerminosRoute
  '/articulos/$id': typeof ArticulosIdRoute
  '/mis-publicaciones/$id': typeof MisPublicacionesIdRoute
  '/vecino/$id': typeof VecinoIdRoute
  '/articulos': typeof ArticulosIndexRoute
  '/mis-publicaciones': typeof MisPublicacionesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/completar-perfil': typeof CompletarPerfilRoute
  '/datos': typeof DatosRoute
  '/entrar': typeof EntrarRoute
  '/mi-cuenta': typeof MiCuentaRoute
  '/mis-solicitudes': typeof MisSolicitudesRoute
  '/moderacion': typeof ModeracionRoute
  '/publicar': typeof PublicarRoute
  '/terminos': typeof TerminosRoute
  '/articulos/$id': typeof ArticulosIdRoute
  '/mis-publicaciones/$id': typeof MisPublicacionesIdRoute
  '/vecino/$id': typeof VecinoIdRoute
  '/articulos/': typeof ArticulosIndexRoute
  '/mis-publicaciones/': typeof MisPublicacionesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/completar-perfil'
    | '/datos'
    | '/entrar'
    | '/mi-cuenta'
    | '/mis-solicitudes'
    | '/moderacion'
    | '/publicar'
    | '/terminos'
    | '/articulos/$id'
    | '/mis-publicaciones/$id'
    | '/vecino/$id'
    | '/articulos/'
    | '/mis-publicaciones/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/completar-perfil'
    | '/datos'
    | '/entrar'
    | '/mi-cuenta'
    | '/mis-solicitudes'
    | '/moderacion'
    | '/publicar'
    | '/terminos'
    | '/articulos/$id'
    | '/mis-publicaciones/$id'
    | '/vecino/$id'
    | '/articulos'
    | '/mis-publicaciones'
  id:
    | '__root__'
    | '/'
    | '/completar-perfil'
    | '/datos'
    | '/entrar'
    | '/mi-cuenta'
    | '/mis-solicitudes'
    | '/moderacion'
    | '/publicar'
    | '/terminos'
    | '/articulos/$id'
    | '/mis-publicaciones/$id'
    | '/vecino/$id'
    | '/articulos/'
    | '/mis-publicaciones/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompletarPerfilRoute: typeof CompletarPerfilRoute
  DatosRoute: typeof DatosRoute
  EntrarRoute: typeof EntrarRoute
  MiCuentaRoute: typeof MiCuentaRoute
  MisSolicitudesRoute: typeof MisSolicitudesRoute
  ModeracionRoute: typeof ModeracionRoute
  PublicarRoute: typeof PublicarRoute
  TerminosRoute: typeof TerminosRoute
  ArticulosIdRoute: typeof ArticulosIdRoute
  MisPublicacionesIdRoute: typeof MisPublicacionesIdRoute
  VecinoIdRoute: typeof VecinoIdRoute
  ArticulosIndexRoute: typeof ArticulosIndexRoute
  MisPublicacionesIndexRoute: typeof MisPublicacionesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/completar-perfil': {
      id: '/completar-perfil'
      path: '/completar-perfil'
      fullPath: '/completar-perfil'
      preLoaderRoute: typeof CompletarPerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datos': {
      id: '/datos'
      path: '/datos'
      fullPath: '/datos'
      preLoaderRoute: typeof DatosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mi-cuenta': {
      id: '/mi-cuenta'
      path: '/mi-cuenta'
      fullPath: '/mi-cuenta'
      preLoaderRoute: typeof MiCuentaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mis-solicitudes': {
      id: '/mis-solicitudes'
      path: '/mis-solicitudes'
      fullPath: '/mis-solicitudes'
      preLoaderRoute: typeof MisSolicitudesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moderacion': {
      id: '/moderacion'
      path: '/moderacion'
      fullPath: '/moderacion'
      preLoaderRoute: typeof ModeracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publicar': {
      id: '/publicar'
      path: '/publicar'
      fullPath: '/publicar'
      preLoaderRoute: typeof PublicarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminos': {
      id: '/terminos'
      path: '/terminos'
      fullPath: '/terminos'
      preLoaderRoute: typeof TerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articulos/': {
      id: '/articulos/'
      path: '/articulos'
      fullPath: '/articulos/'
      preLoaderRoute: typeof ArticulosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articulos/$id': {
      id: '/articulos/$id'
      path: '/articulos/$id'
      fullPath: '/articulos/$id'
      preLoaderRoute: typeof ArticulosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mis-publicaciones/': {
      id: '/mis-publicaciones/'
      path: '/mis-publicaciones'
      fullPath: '/mis-publicaciones/'
      preLoaderRoute: typeof MisPublicacionesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mis-publicaciones/$id': {
      id: '/mis-publicaciones/$id'
      path: '/mis-publicaciones/$id'
      fullPath: '/mis-publicaciones/$id'
      preLoaderRoute: typeof MisPublicacionesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vecino/$id': {
      id: '/vecino/$id'
      path: '/vecino/$id'
      fullPath: '/vecino/$id'
      preLoaderRoute: typeof VecinoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompletarPerfilRoute: CompletarPerfilRoute,
  DatosRoute: DatosRoute,
  EntrarRoute: EntrarRoute,
  MiCuentaRoute: MiCuentaRoute,
  MisSolicitudesRoute: MisSolicitudesRoute,
  ModeracionRoute: ModeracionRoute,
  PublicarRoute: PublicarRoute,
  TerminosRoute: TerminosRoute,
  ArticulosIdRoute: ArticulosIdRoute,
  MisPublicacionesIdRoute: MisPublicacionesIdRoute,
  VecinoIdRoute: VecinoIdRoute,
  ArticulosIndexRoute: ArticulosIndexRoute,
  MisPublicacionesIndexRoute: MisPublicacionesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
