/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompletarPerfilRouteImport } from './routes/completar-perfil'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as MiCuentaRouteImport } from './routes/mi-cuenta'
import { Route as ArticulosIndexRouteImport } from './routes/articulos.index'
import { Route as ArticulosIdRouteImport } from './routes/articulos.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompletarPerfilRoute = CompletarPerfilRouteImport.update({
  id: '/completar-perfil',
  path: '/completar-perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const MiCuentaRoute = MiCuentaRouteImport.update({
  id: '/mi-cuenta',
  path: '/mi-cuenta',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticulosIndexRoute = ArticulosIndexRouteImport.update({
  id: '/articulos/',
  path: '/articulos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticulosIdRoute = ArticulosIdRouteImport.update({
  id: '/articulos/$id',
  path: '/articulos/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/completar-perfil': typeof CompletarPerfilRoute
  '/entrar': typeof EntrarRoute
  '/mi-cuenta': typeof MiCuentaRoute
  '/articulos/$id': typeof ArticulosIdRoute
  '/articulos/': typeof ArticulosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/completar-perfil': typeof CompletarPerfilRoute
  '/entrar': typeof EntrarRoute
  '/mi-cuenta': typeof MiCuentaRoute
  '/articulos/$id': typeof ArticulosIdRoute
  '/articulos': typeof ArticulosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/completar-perfil': typeof CompletarPerfilRoute
  '/entrar': typeof EntrarRoute
  '/mi-cuenta': typeof MiCuentaRoute
  '/articulos/$id': typeof ArticulosIdRoute
  '/articulos/': typeof ArticulosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/completar-perfil'
    | '/entrar'
    | '/mi-cuenta'
    | '/articulos/$id'
    | '/articulos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/completar-perfil'
    | '/entrar'
    | '/mi-cuenta'
    | '/articulos/$id'
    | '/articulos'
  id:
    | '__root__'
    | '/'
    | '/completar-perfil'
    | '/entrar'
    | '/mi-cuenta'
    | '/articulos/$id'
    | '/articulos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompletarPerfilRoute: typeof CompletarPerfilRoute
  EntrarRoute: typeof EntrarRoute
  MiCuentaRoute: typeof MiCuentaRoute
  ArticulosIdRoute: typeof ArticulosIdRoute
  ArticulosIndexRoute: typeof ArticulosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/completar-perfil': {
      id: '/completar-perfil'
      path: '/completar-perfil'
      fullPath: '/completar-perfil'
      preLoaderRoute: typeof CompletarPerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mi-cuenta': {
      id: '/mi-cuenta'
      path: '/mi-cuenta'
      fullPath: '/mi-cuenta'
      preLoaderRoute: typeof MiCuentaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articulos/': {
      id: '/articulos/'
      path: '/articulos'
      fullPath: '/articulos/'
      preLoaderRoute: typeof ArticulosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articulos/$id': {
      id: '/articulos/$id'
      path: '/articulos/$id'
      fullPath: '/articulos/$id'
      preLoaderRoute: typeof ArticulosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompletarPerfilRoute: CompletarPerfilRoute,
  EntrarRoute: EntrarRoute,
  MiCuentaRoute: MiCuentaRoute,
  ArticulosIdRoute: ArticulosIdRoute,
  ArticulosIndexRoute: ArticulosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
